import {cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,beforeEach,expect,it,vi} from "vitest";
import {App} from "../src/App";
import {nativeAdapter} from "../src/editor/adapter";
beforeEach(()=>{localStorage.clear();vi.stubGlobal("PointerEvent",MouseEvent);});
afterEach(()=>{cleanup();vi.restoreAllMocks();vi.unstubAllGlobals();});
it("exports flattened text/ink explicitly without marking editable work saved, and Ctrl+S saves editable by default",async()=>{
 vi.spyOn(nativeAdapter,"openPdf").mockResolvedValue({id:"editable-source",name:"Editable.pdf",pages:[{width:300,height:400}]});
 vi.spyOn(nativeAdapter,"renderPage").mockResolvedValue("data:image/png;base64,");
 vi.spyOn(nativeAdapter as Required<typeof nativeAdapter>,"getPageText").mockResolvedValue({characters:[]});
 const save=vi.spyOn(nativeAdapter,"exportPdf").mockResolvedValue("C:/test/Edited.pdf");
 render(<App initialDemo={false}/>);
 fireEvent.click(screen.getByRole("button",{name:"Open a PDF"}));
 await screen.findByRole("tab",{name:"Editable.pdf"});
 fireEvent.click(screen.getByRole("button",{name:"Text"}));
 const canvas=document.querySelector(".page-canvas")!;
 vi.spyOn(canvas,"getBoundingClientRect").mockReturnValue({left:0,top:0,width:300,height:400,right:300,bottom:400,x:0,y:0,toJSON(){}});
 fireEvent.pointerDown(canvas,{button:0,clientX:40,clientY:80});
 fireEvent.change(await screen.findByRole("textbox",{name:"Content"}),{target:{value:"Keep editable"}});
 fireEvent.click(screen.getByRole("button",{name:"Save options"}));
 expect(screen.getByRole("menu")).toHaveTextContent("Highlights and comments remain annotations");
 fireEvent.click(screen.getByRole("menuitem",{name:"Flatten text and ink"}));
 await waitFor(()=>expect(save).toHaveBeenCalledTimes(1));
 expect(save.mock.calls[0][1]).toEqual({flatten:true});
 expect(screen.getByLabelText("Unsaved changes")).toBeInTheDocument();
 await screen.findByText(/Exported flattened text and ink/);
 fireEvent.keyDown(window,{key:"s",ctrlKey:true});
 await waitFor(()=>expect(save).toHaveBeenCalledTimes(2));
 expect(save.mock.calls[1]).toHaveLength(1);
 await waitFor(()=>expect(screen.queryByLabelText("Unsaved changes")).not.toBeInTheDocument());
});
it("lets keyboard users close save options without changing tools or exporting",async()=>{
 vi.spyOn(nativeAdapter,"openPdf").mockResolvedValue({id:"options",name:"Options.pdf",pages:[{width:300,height:400}]});
 vi.spyOn(nativeAdapter,"renderPage").mockResolvedValue("data:image/png;base64,");
 vi.spyOn(nativeAdapter as Required<typeof nativeAdapter>,"getPageText").mockResolvedValue({characters:[]});
 const save=vi.spyOn(nativeAdapter,"exportPdf").mockResolvedValue(null);
 render(<App initialDemo={false}/>);fireEvent.click(screen.getByRole("button",{name:"Open a PDF"}));
 await screen.findByRole("tab",{name:"Options.pdf"});
 const options=screen.getByRole("button",{name:"Save options"});fireEvent.click(options);
 const first=screen.getByRole("menuitem",{name:"Save editable PDF"});expect(first).toHaveFocus();
 fireEvent.keyDown(first,{key:"ArrowDown"});expect(screen.getByRole("menuitem",{name:"Flatten text and ink"})).toHaveFocus();
 fireEvent.keyDown(screen.getByRole("menuitem",{name:"Flatten text and ink"}),{key:"Escape"});
 expect(screen.queryByRole("menu")).not.toBeInTheDocument();expect(options).toHaveFocus();expect(save).not.toHaveBeenCalled();
});
it("keeps an opened save menu anchored through queued toolbar scroll events", async () => {
 const { SaveCopyButton } = await import("../src/components/SaveCopyButton");
 render(<SaveCopyButton disabled={false} demo={false} onSave={vi.fn()}/>);
 const trigger=screen.getByRole("button",{name:"Save options"});let right=950;
 vi.spyOn(trigger,"getBoundingClientRect").mockImplementation(()=>({left:right-32,right,top:54,bottom:88,width:32,height:34,x:right-32,y:54,toJSON(){}}));
 fireEvent.click(trigger);const menu=screen.getByRole("menu");
 fireEvent.scroll(window);expect(screen.getByRole("menu")).toBe(menu);
 right=880;fireEvent.scroll(window);expect(menu).toHaveStyle({left:"560px",top:"96px"});
 expect(screen.getByRole("menuitem",{name:"Save editable PDF"})).toHaveFocus();
});
it.each([false,true])("returns the menu's keyboard Tab starting point to its trigger (shift=%s)",async shiftKey=>{
 const { SaveCopyButton } = await import("../src/components/SaveCopyButton");
 const save=vi.fn();render(<SaveCopyButton disabled={false} demo={false} onSave={save}/>);
 const trigger=screen.getByRole("button",{name:"Save options"});fireEvent.click(trigger);
 fireEvent.keyDown(screen.getByRole("menuitem",{name:"Save editable PDF"}),{key:"Tab",shiftKey});
 expect(screen.queryByRole("menu")).not.toBeInTheDocument();expect(trigger).toHaveFocus();expect(save).not.toHaveBeenCalled();
});