import { chromium, expect } from "@playwright/test";
const browser = await chromium.launch({ headless: true });
try {
  const context = await browser.newContext({ permissions: ["clipboard-read", "clipboard-write"] });
  const page = await context.newPage();
  for (const rotation of [0, 90, 180, 270]) {
    await page.goto(`http://127.0.0.1:1422/tests/fixtures/page-interactions.html?rotation=${rotation}`);
    const glyphs = page.locator("[data-pdf-character]");
    await expect(glyphs).toHaveCount(21);
    const first = await glyphs.nth(0).boundingBox();
    const last = await glyphs.nth(20).boundingBox();
    const start = rotation === 0 ? [first.x + .2, first.y + first.height / 2] : rotation === 90 ? [first.x + first.width / 2, first.y + .2] : rotation === 180 ? [first.x + first.width - .2, first.y + first.height / 2] : [first.x + first.width / 2, first.y + first.height - .2];
    const end = rotation === 0 ? [last.x + last.width - .2, last.y + last.height / 2] : rotation === 90 ? [last.x + last.width / 2, last.y + last.height - .2] : rotation === 180 ? [last.x + .2, last.y + last.height / 2] : [last.x + last.width / 2, last.y + .2];
    await page.mouse.move(...start);
    await page.mouse.down();
    await page.mouse.move(...end, { steps: 15 });
    await page.mouse.up();
    await page.keyboard.press("Control+c");
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe("Hello PDF\r\nSecond line");
    await page.mouse.move(...end);
    await page.mouse.down();
    await page.mouse.move(...start, { steps: 15 });
    await page.mouse.up();
    await page.keyboard.press("Control+c");
    expect(await page.evaluate(() => navigator.clipboard.readText())).toBe("Hello PDF\r\nSecond line");
    console.log(`Forward/reverse native mouse selection and Ctrl+C preserved lines at ${rotation} degrees / 150% zoom`);
  }
  await page.goto("http://127.0.0.1:1422/tests/fixtures/page-interactions.html");
  const overlay = page.locator("[data-overlay]");
  await overlay.hover();
  await page.mouse.down();
  await page.mouse.move(450, 350, { steps: 10 });
  await page.mouse.up();
  await expect(page.locator("output")).toHaveText("moved overlay");
  await page.getByRole("button", { name: "draw", exact: true }).click();
  const glyph = await page.locator("[data-pdf-character]").first().boundingBox();
  await page.mouse.move(glyph.x + 2, glyph.y + 4);
  await page.mouse.down();
  await page.mouse.move(glyph.x + 60, glyph.y + 20, { steps: 10 });
  await page.mouse.up();
  await expect(page.locator("output")).toHaveText("drew stroke");
  await page.getByRole("button", { name: "text", exact: true }).click();
  await page.mouse.click(glyph.x + 2, glyph.y + 4);
  await expect(page.locator("output")).toHaveText("added text");
  await page.getByRole("button", { name: "signature", exact: true }).click();
  await page.mouse.move(glyph.x + 2, glyph.y + 4);
  await expect(page.locator(".signature-preview")).toBeVisible();
  await page.mouse.click(glyph.x + 2, glyph.y + 4);
  await expect(page.locator("output")).toHaveText("placed signature");
  await page.keyboard.press("Escape");
  await expect(page.locator(".signature-preview")).toHaveCount(0);
  console.log("Existing overlay drag, drawing, text insertion, signature placement and Escape passed");
} finally { await browser.close(); }