import {act,cleanup,fireEvent,render,screen,waitFor} from "@testing-library/react";
import {afterEach,beforeEach,expect,it,vi} from "vitest";
import {App} from "../src/App";
import {nativeAdapter} from "../src/editor/adapter";
import {recoveryApi,snapshotWorkspace} from "../src/editor/recovery";
import {addSession,emptyWorkspace,createSession} from "../src/editor/workspace";
import * as printing from "../src/editor/printing";
const nativeWindow=vi.hoisted(()=>({listen:vi.fn().mockResolvedValue(()=>{})}));
vi.mock("@tauri-apps/api/window",()=>({getCurrentWindow:()=>({onCloseRequested:nativeWindow.listen})}));
beforeEach(()=>{
 localStorage.clear();Object.defineProperty(window,"__TAURI_INTERNALS__",{configurable:true,value:{}});
 vi.spyOn(recoveryApi,"load").mockResolvedValue(null);vi.spyOn(recoveryApi,"save").mockResolvedValue();vi.spyOn(recoveryApi,"clear").mockResolvedValue();
 vi.spyOn(nativeAdapter,"openPdf").mockResolvedValue({id:"source",name:"Example.pdf",pages:[{width:300,height:400}]});
 vi.spyOn(nativeAdapter,"renderPage").mockResolvedValue("data:image/png;base64,");
 vi.spyOn(nativeAdapter as Required<typeof nativeAdapter>,"getPageText").mockResolvedValue({characters:[... "Hello world"].map((text,i)=>({text,x:10+i*8,y:40,width:8,height:12}))});
 vi.spyOn(nativeAdapter,"closeDocument").mockResolvedValue();
 nativeWindow.listen.mockClear();
});
afterEach(()=>{cleanup();delete (window as unknown as Record<string,unknown>).__TAURI_INTERNALS__;vi.restoreAllMocks();});
it("offers pending recovery before opening files and restores editable dirty state",async()=>{
 const tab=createSession({id:"recovered-source",name:"Recovered.pdf",pages:[{width:300,height:400}]},nativeAdapter,110);tab.history.present.pages[0].rotation=90;
 vi.mocked(recoveryApi.load).mockResolvedValue(snapshotWorkspace(addSession(emptyWorkspace(),tab),new Map()));
 render(<App initialDemo={false}/>);
 expect(await screen.findByRole("dialog",{name:"Restore your workspace?"})).toBeInTheDocument();
 expect(recoveryApi.save).not.toHaveBeenCalled();
 fireEvent.click(screen.getByRole("button",{name:"Restore workspace"}));
 expect(await screen.findByRole("tab",{name:"Recovered.pdf"})).toBeInTheDocument();
 expect(screen.getByText("90° clockwise")).toBeInTheDocument();
 expect(screen.getByLabelText("Unsaved changes")).toBeInTheDocument();
 expect(screen.getByRole("button",{name:"110%"})).toBeInTheDocument();
});
it("opens search with Ctrl+F and prints current edits through Ctrl+P",async()=>{
 const print=vi.spyOn(printing,"printPdf").mockResolvedValue(false);
 render(<App initialDemo={false}/>);
 await waitFor(()=>expect(screen.getByRole("button",{name:"Open a PDF"})).toBeEnabled());
 fireEvent.click(screen.getByRole("button",{name:"Open a PDF"}));await screen.findByRole("tab",{name:"Example.pdf"});
 fireEvent.keyDown(window,{key:"f",ctrlKey:true});
 const field=await screen.findByRole("searchbox",{name:"Find in document"});fireEvent.change(field,{target:{value:"world"}});
 await waitFor(()=>expect(screen.getByText("1 of 1")).toBeInTheDocument());
 fireEvent.keyDown(field,{key:"Escape"});
 expect(screen.queryByRole("searchbox",{name:"Find in document"})).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole("button",{name:"Rotate"}));
 fireEvent.keyDown(window,{key:"p",ctrlKey:true});await screen.findByRole("dialog",{name:"Print document"});
 fireEvent.click(screen.getByRole("button",{name:"Choose printer…"}));
 await waitFor(()=>expect(print).toHaveBeenCalled());
 expect(print.mock.calls[0][0][0].rotation).toBe(90);
 expect(screen.getByLabelText("Unsaved changes")).toBeInTheDocument();
});
it("awaits recovery cleanup on confirmed normal close and preserves it on cancel",async()=>{
 render(<App initialDemo={false}/>);
 await waitFor(()=>expect(screen.getByRole("button",{name:"Open a PDF"})).toBeEnabled());
 fireEvent.click(screen.getByRole("button",{name:"Open a PDF"}));await screen.findByRole("tab",{name:"Example.pdf"});
 fireEvent.click(screen.getByRole("button",{name:"Rotate"}));await waitFor(()=>expect(nativeWindow.listen).toHaveBeenCalled());
 const event={preventDefault:vi.fn()};let closing!:Promise<void>;
 act(()=>{closing=nativeWindow.listen.mock.calls[0][0](event);});
 fireEvent.click(await screen.findByRole("button",{name:"Keep editing"}));await act(()=>closing);
 expect(recoveryApi.clear).not.toHaveBeenCalled();
 act(()=>{closing=nativeWindow.listen.mock.calls[0][0]({preventDefault:vi.fn()});});
 fireEvent.click(await screen.findByRole("button",{name:"Discard and close"}));await act(()=>closing);
 expect(recoveryApi.clear).toHaveBeenCalledTimes(1);
});
