import { cleanup, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { App } from "../src/App";
import { nativeAdapter } from "../src/editor/adapter";
beforeEach(()=>{ localStorage.clear(); vi.stubGlobal("PointerEvent",MouseEvent); });
afterEach(()=>{ cleanup(); vi.restoreAllMocks(); vi.unstubAllGlobals(); });
it("edits imported comments, navigates their anchors and keeps review history isolated by tab",async()=>{
 vi.spyOn(nativeAdapter,"openPdf").mockResolvedValueOnce({id:"review-a",name:"Review.pdf",pages:[{width:300,height:400,overlays:[{type:"comment",id:"note",x:40,y:70,text:"Check totals",color:"#FFE066"},{type:"highlight",id:"mark",rects:[{x:40,y:110,width:120,height:12}],color:"#FFE066"}]}]}).mockResolvedValueOnce({id:"review-b",name:"Other.pdf",pages:[{width:300,height:400}]});
 vi.spyOn(nativeAdapter,"renderPage").mockResolvedValue("data:image/png;base64,");
 vi.spyOn(nativeAdapter as Required<typeof nativeAdapter>,"getPageText").mockResolvedValue({characters:[]});
 render(<App initialDemo={false}/>);
 fireEvent.click(screen.getByRole("button",{name:"Open a PDF"}));
 fireEvent.click(await screen.findByRole("button",{name:"Page 1: Check totals"}));
 const note=screen.getByRole("textbox",{name:"Comment"});
 fireEvent.change(note,{target:{value:"Totals checked"}});
 fireEvent.click(screen.getByRole("button",{name:"Open"}));
 await screen.findByRole("tab",{name:"Other.pdf"});
 expect(screen.queryByRole("button",{name:"Page 1: Totals checked"})).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole("tab",{name:"Review.pdf"}));
 fireEvent.click(screen.getByRole("button",{name:"Page 1: Totals checked"}));
 fireEvent.click(screen.getByRole("button",{name:"Delete comment"}));
 expect(screen.queryByRole("button",{name:"Page 1: Totals checked"})).not.toBeInTheDocument();
 fireEvent.click(screen.getByRole("button",{name:"Undo"}));
 expect(screen.getByRole("button",{name:"Page 1: Totals checked"})).toBeInTheDocument();
 fireEvent.click(screen.getByRole("button",{name:"Page 1: Highlight"}));
 expect(screen.getByRole("button",{name:"Delete highlight"})).toBeInTheDocument();
});
it("places a comment and focuses its text immediately",async()=>{
 render(<App initialDemo={false}/>); fireEvent.click(screen.getByRole("button",{name:"Explore demo"}));
 await screen.findByRole("tab",{name:"Folio welcome.pdf"});
 fireEvent.click(screen.getByRole("button",{name:"Comment"}));
 const canvas=document.querySelector(".page-canvas")!;
 vi.spyOn(canvas,"getBoundingClientRect").mockReturnValue({left:0,top:0,width:612,height:792,right:612,bottom:792,x:0,y:0,toJSON(){}});
 fireEvent.pointerDown(canvas,{button:0,clientX:100,clientY:200});
 const input=await screen.findByRole("textbox",{name:"Comment"});
 await waitFor(()=>expect(input).toHaveFocus());
 fireEvent.change(input,{target:{value:"Follow up"}});
 expect(screen.getByRole("button",{name:"Page 1: Follow up"})).toBeInTheDocument();
});